### ISSUE TITLE
Run e2e against different hosted k8s offerings

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1257]
Currently we are running e2e exclusively against GKE. 
To ensure incoming changes don't break compatibility with other hosted k8s offerings we should run the e2e tests at least in certain intervals (daily?) against the other supported environments: 
* EKS
* AKS

Work required:
- [x] Create common tool for provisioning - #1431
- [x] Add support for GKE - #1431
- [x] Add support for AKS - #1497
- [x] Move CI to deployer - #1515
- [x] Move dev targets to deployer - #1594 
- [x] Add support for EKS #2633

**Comment by artemnikitin** [comment]
I think daily will be sufficient as we do it like that for different versions in GKE https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/

**Comment by david-kow** [comment]
This is effectively blocked on https://github.com/elastic/cloud/issues/39989, since Sep 16.
