### ISSUE TITLE
Meta-issue: StatefulSet refactoring

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1299]
The work on refactoring our orchestration layer to use StatefulSets started with https://github.com/elastic/cloud-on-k8s/issues/1173, in the `statefulset-refactoring` feature branch.

Steps:

- [x] [Migrate from pods to StatefulSets](https://github.com/elastic/cloud-on-k8s/pull/1205)
- [x] [Support for StatefulSet scale up/down](https://github.com/elastic/cloud-on-k8s/pull/1218)
- [x] [Support StatefulSets rolling upgrades (PV reuse)](https://github.com/elastic/cloud-on-k8s/pull/1219)
- [x] [Improve zen1 & zen2 support](https://github.com/elastic/cloud-on-k8s/pull/1262)
- [x] [Refactor/cleanup driver & pod creation logic towards simplification](https://github.com/elastic/cloud-on-k8s/pull/1295)
- [x] [Get E2E tests green](https://github.com/elastic/cloud-on-k8s/pull/1459)
- [x] [Merge the `statefulset-refactoring` feature branch into `master`](https://github.com/elastic/cloud-on-k8s/pull/1463)

Then, several tasks can be achieved in parallel:
- [x] [Add missing StatefulSets unit tests](https://github.com/elastic/cloud-on-k8s/issues/1287)
- [x] [Improve zen1 support](https://github.com/elastic/cloud-on-k8s/issues/1281)
- [x] [Remove PVCs when removing StatefulSets](https://github.com/elastic/cloud-on-k8s/issues/1288)
- [x] [Improve zen1/zen2 support in rolling upgrades](https://github.com/elastic/cloud-on-k8s/issues/1289)
- [x] [Make sure emptyDirs are correctly supported](https://github.com/elastic/cloud-on-k8s/issues/1291)
- [ ] [Account for maxSurge during StatefulSet replacements](https://github.com/elastic/cloud-on-k8s/issues/1292)
- [x] [Add more rolling upgrade e2e tests](https://github.com/elastic/cloud-on-k8s/issues/1156)
- [x] [Warn user about impossible PVC resize](https://github.com/elastic/cloud-on-k8s/issues/1293)
- [x] [Improve rolling upgrade health checks](https://github.com/elastic/cloud-on-k8s/issues/1155)
- [x] [Rely on maxUnavailable during rolling upgrades](https://github.com/elastic/cloud-on-k8s/issues/1294)
- [ ] [Implement grow and shrink](https://github.com/elastic/cloud-on-k8s/issues/1290) - delayed to later/non-urgent

**Comment by sebgl** [comment]
I'm closing this now. Most issues have been solved already. https://github.com/elastic/cloud-on-k8s/issues/1292 is in progress and will be solved pretty soon.

The only remaining issue is https://github.com/elastic/cloud-on-k8s/issues/1290, to support cluster mutations in a grow-and-shrink fashion (instead of rolling upgrades). This is partially implemented when adding/removing StatefulSets, but not when replacing Pods of an existing StatefulSet, for which we always default to rolling upgrades. We may decide to not implement it though, since rolling upgrades is the default documented way of operating Elasticsearch.
