### ISSUE TITLE
[META] Documentation plan for Beta v1.0.0

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1734]
Moving to StatefulSet-based orchestration, some of the current documentation is no longer accurate and the following updates are required:

- [x] Add a new section about node orchestration - #1758  (@sebgl, @barkbay, @pebrc)
- [x] Add a new section "Running Kibana on ECK" - #1389 (@barkbay)
- [x] Add a glossary - #1744 (@alaudazzi)
- [x] Update Node scheduling section - #1763  (@sebgl)
- [x] Update strategy section - #1762 (@david-kow)
- [x] Update Troubleshooting section - #1761 (@thbkrkr)
- [x] Remove redundancies between JVM heap size and Managing compute resources - #1785  (@charith-elastic)
- [X] Remove Group Definition section - #1751 (@thbkrkr)
- [x] Upgrade your cluster - #1143, #1144 (@sebgl)
- [x] Document operator configuration options - #1379 (@anyasabo)
- [x] Make ECK requirements more explicit in the documentation - #1858 (@alaudazzi)
- [x] Make k8s nodes vs. Elasticsearch explicit in docs - #1851 (@anyasabo)
- [x] Updated the cloud-on-k8s README.md - #1890 (@alaudazzi)

**Comment by sebgl** [comment]
As per https://github.com/elastic/cloud-on-k8s/pull/1736#issue-317868353, let's not forget to document that PVCs are removed automatically.

**Comment by alaudazzi** [comment]
Relates to #1758
