### ISSUE TITLE
[META] Elastic Stack 8.0 upgrade

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2599]
This meta issue will track work needed for upgrading Elastic Stack to 8.0 in ECK. This issue will evolve as new, required changes are being discovered.

### Documentation tracking

8.0 breaking changes documentation is available today and to avoid scanning it repeatedly I'll be updating here what was read/analyzed until a given git sha.

* Elasticsearch

  Docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-8.0.html
Relavant path: `elastic/elasticsearch/docs/reference/migration` ([link](https://github.com/elastic/kibana/tree/master/docs/migration))
Analyzed up to commit: `a9afdd7611bc3c3efdb257546933de55d123fe07` ([link](https://github.com/elastic/elasticsearch/commit/a9afdd7611bc3c3efdb257546933de55d123fe07))

* Kibana

  Docs: https://www.elastic.co/guide/en/kibana/master/breaking-changes-8.0.html
Relevant path: `elastic/kibana/docs/migration` ([link](https://github.com/elastic/kibana/tree/master/docs/migration))
Analyzed up to commit: `79ecc408df62a796f6d1ceecb912e30d430c8d53` ([link](https://github.com/elastic/kibana/commit/79ecc408df62a796f6d1ceecb912e30d430c8d53))

* APM Server

  No documentation available yet.

### Testing

The additional testing needs to include:

- upgrade testing (7.x to 8.0)
- ECK e2e tests on 8.0

### Code analysis

We have a number of places where we assume nothing else other than major 6 and 7 exists.

## Work tracking

- [x] Introduce v8 ES client (#2613)
- [x] Replace sync flush with flush for ES 8.0+ (#2445)
- [x] Add major 8 to supported versions (https://github.com/elastic/cloud-on-k8s/issues/2607, #2613)
- [x] Elasticsearch 8.0.0-SNAPSHOT fails at startup due to volume permissions (https://github.com/elastic/cloud-on-k8s/issues/2791)
- ~[ ] Kibana 8.0 gets OOMKilled during initialization with default (1Gi) memory limit (https://github.com/elastic/cloud-on-k8s/issues/3344)~
- [x] Add E2E tests for Elastic Stack 8.0.0-SNAPSHOT (https://github.com/elastic/cloud-on-k8s/issues/2608)
- [x] Add 7.x to 8.0 upgrade test (https://github.com/elastic/cloud-on-k8s/issues/4953)
- [x] Set node names in the voting config exclusions API call (https://github.com/elastic/cloud-on-k8s/issues/2951)
- [x] Don't use deprecated `accept_enterprise` query param (https://github.com/elastic/cloud-on-k8s/issues/4959)

**Comment by pebrc** [comment]
Closing as 8.0 upgrade is out.
