### ISSUE TITLE
Replace stack-controller with associations 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#372]
As outlined in  #283 and #271 we could represent the relationship between Elasticsearch, Kibana and other stack applications we will support in the future via associations instead of a dedicated stack controller. 

- [x] create[ a user CRD](https://github.com/elastic/k8s-operators/issues/416)
- [x] refactor user [handling to use CRD](https://github.com/elastic/k8s-operators/issues/416)
- [x] introduce [KibanaElasticsearchAssociation](https://github.com/elastic/k8s-operators/issues/417)
- [x] introduce [association controller](https://github.com/elastic/k8s-operators/issues/417)

### Option 1 
Dedicated CRD with separate controller
Pro: 
* simple implemenation
Con 
* reproduces 99 % of the functionality of the regular assocation CRD/controller

### Option 2
Introduce a type attribute on the assocation
```
apiVersion: k8s.elastic.co/v1alpha1
kind: KibanaElasticsearchAssociation
metadata:
  name: foo-bar
  namespace: elastic
spec:
  monitoring: 
      name: <monitoring-cluster-name if different from below>
      namespace: <monitoring-cluster-namespace>
  elasticsearch:
    name: <name of ElasticsearchCluster resource>
    namespace: foo
  kibana:
    name: <name of Kibana resource>
    namespace: bar

```

Pro 
* better sharing of common functionality 
* one controller less to run one CRD less to create
* invariant that monitoring cluster needs to contain data of Elasticsearch source cluster is enforce by having both relationships in one CRD

Con
* not sure how idiomatic the naming choice `type:elasticsearch` is

## Chosen option
We decided to go with the amended version of option 2
