### ISSUE TITLE
7.0 support 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#389]
Related to #231 

We have implemented support for zen2 discovery via the version specific driver mechanism. But 7.0 brings other breaking changes that we need to consider and support if necessary.

## Tasks

- [x] Potential candidate: ~`:` no longer allowed in cluster or index name: we need a validation for that.~ 
     Out of scope. Part of major version upgrades
- [x] Potential candidate: ~realm settings changes, explicit type no longer supported~
        Out of scope. Part of major version upgrades
- [x] Potential candidate: trial license security defaults have changed [not relevant as we don't rely on defaults but set security explicitly]
- [x] Go through [7.0 breaking changes docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html) and identify other issues affecting us.
         Looks ok so far.
