### ISSUE TITLE
[Meta] Autoscaling

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3999]
The aim of this meta issue is to track the effort to have an initial support for the Elasticsearch autoscaling API.
You can use this issue to let me know if something is missing or for any question regarding the scope of the first release.

- [x] [Discuss nodeSets and Elasticsearch autoscaling policy API](https://github.com/elastic/cloud-on-k8s/issues/3955)
- [x] [Autoscaling spec place holder](https://github.com/elastic/cloud-on-k8s/issues/3998)
- [x] [Autoscaling spec first version and behaviour/stabilization configuration](https://github.com/elastic/cloud-on-k8s/issues/4006)
- [x] [User notifications and status API](https://github.com/elastic/cloud-on-k8s/issues/4024)
- [x] [Dynamic scaling of cpu requests](https://github.com/elastic/cloud-on-k8s/issues/4021)
- [x] [Dynamic scaling of memory requests with storage deciders](https://github.com/elastic/cloud-on-k8s/issues/4076)
- [ ] Cluster migration: from manually managed resources to autoscaled and vice versa
- [x] [Use of `current_capacity`](https://github.com/elastic/cloud-on-k8s/pull/4250)
- [x] Blocker: [Elasticsearch should auto-determine appropriate machine memory settings](https://github.com/elastic/elasticsearch/issues/65025)

Testing and documentation:

- [ ] Initiate user documentation, inc. overlapping roles issue
- [x] Limitation: only 1 single volume is supported in alpha
- [ ] For ECK contributors: document the design and the architecture 
- [ ] Discuss a test strategy for the autoscaling feature

**Comment by barkbay** [comment]
Except documentation and bugs, the last 2 PRs for the first alpha release are https://github.com/elastic/cloud-on-k8s/pull/4264 and https://github.com/elastic/cloud-on-k8s/pull/4265

**Comment by barkbay** [comment]
Documentation and tests are tracked in https://github.com/elastic/cloud-on-k8s/issues/4277 and https://github.com/elastic/cloud-on-k8s/issues/4276

I'm closing this issue as the first version of autoscaling for Elasticsearch has been implemented in the PR listed [here](https://github.com/elastic/cloud-on-k8s/pulls?q=is%3Apr+is%3Aclosed+label%3Av1.5.0+label%3Aautoscaling+).
